name: ci 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

